openapi: 3.0.1
info:
  title: Documentación del Ecommerce de Ribot
  description: E-commerce
servers:
  - url: http://localhost:8080
paths:
  /api/carts:
    get:
      summary: Obtener todos los carritos
      tags:
        - Carritos
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  carts:
                    type: array
                    items:
                      $ref: "#/components/schemas/Cart"
    post:
      summary: Agregar un nuevo carrito
      tags:
        - Carritos
      parameters:
        - in:
          name: email por loggeo
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
  /api/carts/{cid}:
    get:
      summary: Obtener un carrito por su ID
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
    put:
      summary: Actualizar un carrito por su ID
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cart"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
    delete:
      summary: Eliminar un carrito por su ID
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
  /api/carts/{cid}/product/{pid}:
    post:
      summary: Agregar un producto con su pid a un carrito con su cid
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
        - in: path
          name: pid
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
    put:
      summary: Actualizar un producto con su pid en un carrito con su cid
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
        - in: path
          name: pid
          requided: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cart"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
    delete:
      summary: Eliminar un producto con su pid de un carrito con su cid
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
        - in: path
          name: pid
          required: true
          schea:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
  /api/carts/{cid}/purchase:
    get:
      summary: Genera el ticket de compra
      tags:
        - Carritos
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ticket:
                    type: string
                  amount:
                    type: number
                  productos:
                    $ref: "#/components/schemas/Product"
components:
  schemas:
    Cart:
      type: object
      properties:
        products:
          type: array
          items:
            type: object
            properties:
              product:
                $ref: "#/components/schemas/Product"
              quantity:
                type: number
        user:
          type: string
